services:
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: stockmesh-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
      - redis

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: stockmesh-sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StockMeshPassw0rd!
    volumes:
      - sqlserver-data:/var/opt/mssql

  redis:
    image: redis:7-alpine
    container_name: stockmesh-redis
    ports:
      - "6379:6379"

volumes:
  sqlserver-data: